import { CheckCircle2, CircleDashed, Sparkles } from "lucide-react";
import { calculateProfileCompleteness } from "@/domains/career/completeness";
import { ExperienceForm } from "@/domains/career/experience-form";
import { KnowledgeForm } from "@/domains/career/knowledge-form";
import { ProfileEditor } from "@/domains/career/profile-editor";
import { storedResumeAnalysisSchema } from "@/domains/career/resume/analysis-schema";
import { ResumeAnalysisReport, ResumeReviewForm } from "@/domains/career/resume/review-form";
import { ResumeUpload } from "@/domains/career/resume/resume-upload";
import { requireSession } from "@/domains/settings/auth/session";
import { prisma } from "@/shared/db/prisma";
import { Card } from "@/shared/ui/card";

const dateValue = (value: Date | null) => value?.toISOString().slice(0, 10) ?? "";

export default async function CareerProfilePage() {
  const session = await requireSession();
  const [profile, pendingSuggestion, acceptedSuggestion] = await Promise.all([
    prisma.careerProfile.findUnique({ where: { userId: session.user.id }, include: { experiences: { orderBy: { startDate: "desc" }, include: { achievements: { orderBy: { createdAt: "desc" } } } }, projects: { orderBy: { createdAt: "desc" } }, careerSkills: { include: { skill: true }, orderBy: { createdAt: "asc" } }, education: { orderBy: { graduationDate: "desc" } }, certifications: { orderBy: { issueDate: "desc" } } } }),
    prisma.memorySuggestion.findFirst({ where: { userId: session.user.id, status: "PENDING", source: { startsWith: "resume:" } }, orderBy: { createdAt: "desc" } }),
    prisma.memorySuggestion.findFirst({ where: { userId: session.user.id, status: "ACCEPTED", source: { startsWith: "resume:" } }, orderBy: { reviewedAt: "desc" } }),
  ]);
  const parsedDraft = pendingSuggestion ? storedResumeAnalysisSchema.safeParse(pendingSuggestion.proposedFact) : null;
  const pendingAnalysis = parsedDraft?.success ? parsedDraft.data : null;
  const parsedAccepted = acceptedSuggestion ? storedResumeAnalysisSchema.safeParse(acceptedSuggestion.proposedFact) : null;
  const acceptedAnalysis = parsedAccepted?.success ? parsedAccepted.data : null;
  const completeness = profile ? calculateProfileCompleteness({ ...profile, experienceCount: profile.experiences.length, skillCount: profile.careerSkills.length, educationCount: profile.education.length }) : 0;
  const salaryExpectation = profile?.salaryExpectation as { notes?: string } | null;

  return <main className="mx-auto max-w-7xl px-5 py-10 sm:px-8"><div className="flex flex-wrap items-end justify-between gap-5"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-[var(--accent)]">Career Knowledge Graph</p><h1 className="mt-2 font-[family-name:var(--font-display)] text-5xl tracking-[-.04em]">Your whole career, verified.</h1><p className="mt-3 max-w-2xl text-[var(--muted)]">Documents come from this profile. AI suggestions never change it without your approval.</p></div><div className="rounded-2xl border border-[var(--line)] bg-white/65 px-5 py-4"><span className="text-xs font-bold uppercase tracking-[.15em] text-[var(--muted)]">Completeness</span><span className="ml-4 text-2xl font-bold">{completeness}%</span></div></div>
    {pendingSuggestion && pendingAnalysis ? <Card className="mt-10 p-6 sm:p-8"><div className="mb-7 flex items-center gap-3"><Sparkles className="size-5 text-[var(--accent)]" /><div><h2 className="text-xl font-bold">Review extracted information</h2><p className="text-sm text-[var(--muted)]">Pending - not part of your verified profile yet.</p></div></div><ResumeReviewForm suggestionId={pendingSuggestion.id} draft={pendingAnalysis} /></Card> : null}
    {!profile && !pendingAnalysis ? <Card className="mt-10 p-6 sm:p-8"><h2 className="font-[family-name:var(--font-display)] text-3xl">Start with the resume you already have</h2><p className="mb-7 mt-2 text-[var(--muted)]">AI will extract a comprehensive, evidence-grounded draft for you to review.</p><ResumeUpload /></Card> : null}
    {profile ? <><div className="mt-10 grid gap-6 lg:grid-cols-[.85fr_1.15fr]"><Card className="p-6 sm:p-8"><h2 className="text-xl font-bold">Profile foundation</h2><p className="mb-6 mt-1 text-sm text-[var(--muted)]">Edit any value directly. Your edits are authoritative.</p><ProfileEditor profile={{ headline: profile.headline ?? "", summary: profile.summary ?? "", targetRole: profile.targetRole ?? "", preferredLocations: profile.preferredLocations, remotePreference: profile.remotePreference, careerGoals: profile.careerGoals, salaryExpectation: salaryExpectation?.notes ?? "" }} /></Card><div className="grid content-start gap-6">
      <Card className="p-6 sm:p-8"><div className="flex flex-wrap items-center justify-between gap-4"><div><h2 className="text-xl font-bold">Experience</h2><p className="mt-1 text-sm text-[var(--muted)]">Manual entries and edits are verified user facts.</p></div><ExperienceForm /></div><div className="mt-6 grid gap-3">{profile.experiences.length ? profile.experiences.map((experience) => <div key={experience.id} className="rounded-2xl border border-[var(--line)] bg-white/55 p-4"><div className="flex justify-between gap-4"><div><p className="font-bold">{experience.title}</p><p className="text-sm text-[var(--muted)]">{experience.company}</p></div>{experience.verified ? <CheckCircle2 className="size-5 text-[var(--focus)]" /> : <CircleDashed className="size-5 text-amber-600" />}</div><p className="mt-3 whitespace-pre-wrap text-sm leading-6">{experience.description}</p><div className="mt-3 flex flex-wrap gap-2"><ExperienceForm experience={{ id: experience.id, company: experience.company, title: experience.title, startDate: dateValue(experience.startDate), endDate: dateValue(experience.endDate), current: experience.current, description: experience.description }} /><KnowledgeForm kind="achievement" initial={{ experienceId: experience.id }} /></div>{experience.achievements.length ? <div className="mt-4 grid gap-2">{experience.achievements.map((achievement) => <div className="rounded-lg bg-[var(--paper)] p-3 text-sm" key={achievement.id}><p>{achievement.description}</p>{achievement.metric ? <p className="mt-1 font-bold">{achievement.metric}</p> : null}<div className="mt-2"><KnowledgeForm kind="achievement" initial={{ id: achievement.id, experienceId: experience.id, description: achievement.description, metric: achievement.metric ?? "", quantified: String(achievement.quantified) }} /></div></div>)}</div> : null}</div>) : <p className="rounded-2xl border border-dashed border-[var(--line)] p-6 text-sm text-[var(--muted)]">No experience added yet.</p>}</div></Card>
      <KnowledgeCard title="Skills" add={<KnowledgeForm kind="skill" />} empty={!profile.careerSkills.length}>{profile.careerSkills.map(({ skill, proficiency }) => <Fact key={skill.id} title={skill.name} detail={[skill.category, proficiency].filter(Boolean).join(" - ")} edit={<KnowledgeForm kind="skill" initial={{ id: skill.id, name: skill.name, category: skill.category, proficiency: proficiency ?? "" }} />} />)}</KnowledgeCard>
      <KnowledgeCard title="Projects" add={<KnowledgeForm kind="project" />} empty={!profile.projects.length}>{profile.projects.map((project) => <Fact key={project.id} title={project.name} detail={project.description} edit={<KnowledgeForm kind="project" initial={{ id: project.id, name: project.name, description: project.description, impact: project.impact ?? "", technologies: project.technologies }} />} />)}</KnowledgeCard>
      <KnowledgeCard title="Education" add={<KnowledgeForm kind="education" />} empty={!profile.education.length}>{profile.education.map((education) => <Fact key={education.id} title={education.school} detail={[education.degree, education.field].filter(Boolean).join(" - ")} edit={<KnowledgeForm kind="education" initial={{ id: education.id, school: education.school, degree: education.degree ?? "", field: education.field ?? "", graduationDate: dateValue(education.graduationDate) }} />} />)}</KnowledgeCard>
      <KnowledgeCard title="Certifications" add={<KnowledgeForm kind="certification" />} empty={!profile.certifications.length}>{profile.certifications.map((certification) => <Fact key={certification.id} title={certification.name} detail={certification.issuer} edit={<KnowledgeForm kind="certification" initial={{ id: certification.id, name: certification.name, issuer: certification.issuer, issueDate: dateValue(certification.issueDate), expirationDate: dateValue(certification.expirationDate) }} />} />)}</KnowledgeCard>
      {!pendingAnalysis ? <Card className="p-6"><details><summary className="cursor-pointer font-bold">Upload another base resume</summary><div className="mt-5"><ResumeUpload /></div></details></Card> : null}
    </div></div>{acceptedAnalysis && !pendingAnalysis ? <Card className="mt-6 p-6 sm:p-8"><details><summary className="cursor-pointer text-xl font-bold">Latest AI resume report</summary><div className="mt-6"><ResumeAnalysisReport report={acceptedAnalysis.report} provenance={acceptedAnalysis.provenance} /></div></details></Card> : null}</> : null}
  </main>;
}

function KnowledgeCard({ title, add, empty, children }: { title: string; add: React.ReactNode; empty: boolean; children: React.ReactNode }) {
  return <Card className="p-6 sm:p-8"><div className="flex items-center justify-between gap-4"><h2 className="text-xl font-bold">{title}</h2>{add}</div><div className="mt-4 grid gap-3">{empty ? <p className="text-sm text-[var(--muted)]">No {title.toLowerCase()} added yet.</p> : children}</div></Card>;
}

function Fact({ title, detail, edit }: { title: string; detail: string; edit: React.ReactNode }) {
  return <div className="rounded-xl border border-[var(--line)] bg-white/55 p-4"><p className="font-bold">{title}</p>{detail ? <p className="mt-1 whitespace-pre-wrap text-sm text-[var(--muted)]">{detail}</p> : null}<div className="mt-3">{edit}</div></div>;
}
