-- CareerOS accesses PostgreSQL only from trusted server code through Prisma.
-- Remove browser Data API access and keep RLS enabled as defense in depth.
REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA public FROM anon, authenticated;
REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public FROM anon, authenticated;
REVOKE ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public FROM anon, authenticated;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public
  REVOKE ALL PRIVILEGES ON TABLES FROM anon, authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public
  REVOKE ALL PRIVILEGES ON SEQUENCES FROM anon, authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public
  REVOKE ALL PRIVILEGES ON FUNCTIONS FROM anon, authenticated;

ALTER TABLE IF EXISTS public."user" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."session" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."account" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."verification" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."career_profile" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."experience" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."project" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."skill" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."career_skill" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."achievement" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."education" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."certification" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."document" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."document_version" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."company" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."job_posting" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."application" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."timeline_event" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."memory_suggestion" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."knowledge_snapshot" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."generation_log" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."knowledge_embedding" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."career_metric" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."_prisma_migrations" ENABLE ROW LEVEL SECURITY;
