import { requireSession } from "@/domains/settings/auth/session";
import { Card } from "@/shared/ui/card";

export default async function SettingsPage() {
  const session = await requireSession();
  const integrations = [
    ["OpenAI document generation", Boolean(process.env.OPENAI_API_KEY)],
    ["Google sign-in", Boolean(process.env.GOOGLE_CLIENT_ID && process.env.GOOGLE_CLIENT_SECRET)],
    ["Production object storage adapter", false],
  ] as const;
  return <main className="mx-auto max-w-5xl px-5 py-10 sm:px-8"><p className="text-sm font-bold uppercase tracking-wider text-[var(--accent)]">Settings and privacy</p><h1 className="mt-2 font-[family-name:var(--font-display)] text-5xl">Your data stays yours.</h1><div className="mt-8 grid gap-5 md:grid-cols-2"><Card className="p-6"><h2 className="text-lg font-bold">Account</h2><dl className="mt-4 space-y-3 text-sm"><div><dt className="font-bold">Name</dt><dd className="text-[var(--muted)]">{session.user.name}</dd></div><div><dt className="font-bold">Email</dt><dd className="text-[var(--muted)]">{session.user.email}</dd></div></dl></Card><Card className="p-6"><h2 className="text-lg font-bold">Integration status</h2><ul className="mt-4 space-y-3">{integrations.map(([name, ready]) => <li className="flex items-center justify-between gap-4 text-sm" key={name}><span>{name}</span><span className={`rounded-full px-2 py-1 text-xs font-bold ${ready ? "bg-[var(--lime)]" : "bg-[var(--paper)] text-[var(--muted)]"}`}>{ready ? "Configured" : "Unavailable"}</span></li>)}</ul><p className="mt-4 text-xs leading-5 text-[var(--muted)]">Resume and cover-letter generation uses OpenAI when configured. Outputs are schema-validated, checked against verified fact IDs, and saved with exact model and prompt provenance.</p></Card><Card className="p-6 md:col-span-2"><h2 className="text-lg font-bold">Privacy model</h2><ul className="mt-4 grid gap-3 text-sm leading-6 text-[var(--muted)] md:grid-cols-2"><li>Career facts are private and owner-scoped.</li><li>Configured AI requests use no-store mode and a pseudonymous safety identifier.</li><li>Factual suggestions require explicit review before profile changes.</li><li>Submitted applications retain exact immutable document versions.</li><li>Secrets and resume binaries are never committed to Git.</li><li>Production storage fails closed until its adapter is implemented.</li></ul></Card></div></main>;
}
